'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LauncherEditor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [COMMANDS]
        '''-extract Background.bmp, BITMAP,103
        '''-extract Play.bmp, BITMAP,105
        '''-extract PlayLit.bmp, BITMAP,114
        '''-extract Options.bmp, BITMAP,259
        '''-extract OptionsLit.bmp, BITMAP,119
        '''-extract Support.bmp, BITMAP,261
        '''-extract SupportLit.bmp, BITMAP,265
        '''-extract Exit.bmp, BITMAP,107
        '''-extract ExitLit.bmp, BITMAP,116.
        '''</summary>
        Friend ReadOnly Property F4Extract() As String
            Get
                Return ResourceManager.GetString("F4Extract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [COMMANDS]
        '''-addoverwrite Background.bmp, BITMAP,103
        '''-addoverwrite Play.bmp, BITMAP,105
        '''-addoverwrite PlayLit.bmp, BITMAP,114
        '''-addoverwrite Options.bmp, BITMAP,259
        '''-addoverwrite OptionsLit.bmp, BITMAP,119
        '''-addoverwrite Support.bmp, BITMAP,261
        '''-addoverwrite SupportLit.bmp, BITMAP,265
        '''-addoverwrite Exit.bmp, BITMAP,107
        '''-addoverwrite ExitLit.bmp, BITMAP,116.
        '''</summary>
        Friend ReadOnly Property F4Replace() As String
            Get
                Return ResourceManager.GetString("F4Replace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [COMMANDS]
        '''-extract Background.bmp, BITMAP,103
        '''-extract Play.bmp, BITMAP,105
        '''-extract PlayLit.bmp, BITMAP,114
        '''-extract Options.bmp, BITMAP,120
        '''-extract OptionsDark.bmp, BITMAP,208
        '''-extract OptionsLit.bmp, BITMAP,119
        '''-extract DataFiles.bmp, BITMAP,117
        '''-extract DataFilesDark.bmp, BITMAP,207
        '''-extract DataFilesLit.bmp, BITMAP,118
        '''-extract TechSupport.bmp, BITMAP,121
        '''-extract TechSupportLit.bmp, BITMAP,122
        '''-extract Exit.bmp, BITMAP,107
        '''-extract ExitLit.bmp, BITMAP,116
        '''-extract Install.bmp, BITMAP,2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FExtract() As String
            Get
                Return ResourceManager.GetString("FExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [COMMANDS]
        '''-addoverwrite Background.bmp, BITMAP,103
        '''-addoverwrite Play.bmp, BITMAP,105
        '''-addoverwrite PlayLit.bmp, BITMAP,114
        '''-addoverwrite Options.bmp, BITMAP,120
        '''-addoverwrite OptionsDark.bmp, BITMAP,208
        '''-addoverwrite OptionsLit.bmp, BITMAP,119
        '''-addoverwrite DataFiles.bmp, BITMAP,117
        '''-addoverwrite DataFilesDark.bmp, BITMAP,207
        '''-addoverwrite DataFilesLit.bmp, BITMAP,118
        '''-addoverwrite TechSupport.bmp, BITMAP,121
        '''-addoverwrite TechSupportLit.bmp, BITMAP,122
        '''-addoverwrite Exit.bmp, BITMAP,107
        '''-add [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FReplace() As String
            Get
                Return ResourceManager.GetString("FReplace", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
